version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: weekplanner-api_client
    restart: always
  backend:
    build:
      context: .
      dockerfile: ./web-api/Dockerfile
    depends_on:
      - db
    links:
      - db
    image: web-api
    restart: always
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3307
    ports:
      - '3307:3307'
    expose:
      - '3307'