version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./weekplanner/Dockerfile
    image: weekplanner
  api:
    build:
      context: .
      dockerfile: ./api-client/Dockerfile
    image: api-client
  backend:
    build:
      context: .
      dockerfile: ./web-api/Dockerfile
    links:
      - db
    image: web-api
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'